name: Production Build & Deploy

on:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install - Root
        run: |
          yarn install
      - name: Yarn install - Client
        working-directory: client
        run: |
          yarn install
      - name: Yarn install - Serverless
        working-directory: serverless
        run: |
          yarn install
      - name: Tests
        run: |
          yarn test
  build-frontend:
    needs: [run-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Store build folder for e2e tests
        uses: actions/upload-artifact@v1
        with:
          name: client
          path: client
  deploy-ci-backend:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install
        run: |
          yarn install
      - name: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SERVERLESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_AWS_SECRET_ACCESS_KEY }}
        run: |
          npx serverless deploy --stage ci
  e2e-test:
    needs: [deploy-ci-backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: download build folder
        uses: actions/download-artifact@v1
        with:
          name: client
      - name: serve build folder
        run: |
          yarn run serve -l 3000 ./build
      - name: run e2e tests
        run: |
          yarn run e2e
  deploy-prod-backend:
    needs: [e2e-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install
        run: |
          yarn install
      - name: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SERVERLESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_AWS_SECRET_ACCESS_KEY }}
        run: |
          npx serverless deploy --stage prod
  deploy-frontend:
    needs: [deploy-prod-backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
        env:
          REACT_APP_STAGE: prod
          REACT_APP_API_BASE: https://iy3gq5bmlg.execute-api.eu-west-2.amazonaws.com
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'client/build'
