name: Pull request build

on:
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install - Root
        run: |
          yarn install
      - name: Yarn install - Take Test App
        working-directory: take-test-app
        run: |
          yarn install
      - name: Yarn install - API
        working-directory: api
        run: |
          yarn install
      - name: Tests
        run: |
          yarn test
  build-test-taking-app:
    needs: [run-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: take-test-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
  build-reviewer-app:
    needs: [run-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reviewer-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'
      - name: Yarn install
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
