openapi: '3.0.0'
info:
  title: Covid19 Antibody Test API
  version: 1.0.0
paths:
  /generate:
    post:
      summary: Generate a new test run for the authorised user
      security:
        - Authentication: []
      responses:
        '200':
          description: An object containing the information for the current test run
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRecord'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authorised
  /interpret:
    post:
      summary: Interpret the currently uploaded image for the current user
      security:
        - Authentication: []
      responses:
        '200':
          description: An object containing the updated test record for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRecord'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authorised
  /update:
    post:
      summary: Update the existing test record
      security:
        - Authentication: []
      responses:
        '200':
          description: An object containing the updated test record for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRecord'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authorised
components:
  securitySchemes:
    Authentication:
      in: header
      type: apiKey
      name: Authorization
      description: "Temporary API key scheme during development"
  schemas:
    TestRecord:
      type: object
      example:
        guid: '94408fed-531c-4353-9f82-a04dc07c2af7'
        uploadUrl: 'https://upload.url.example'
        downloadUrl: 'https://download.url.example'
        step: checkYourKit
      properties:
        guid:
          type: string
          description: The GUID for the user
        uploadUrl:
          type: string
          description: A pre-signed S3 URL for uploading the image
        downloadUrl:
          type: string
          description: A pre-signed S3 URL for viewing the uploaded image
        step:
          type: string
          description: The current step the user is on in the test flow
        timerStartedAt:
          type: number
          description: The time the user begun the timer for the antibody test
        predictionData:
          $ref: '#/components/schemas/PredictionData'
    PredictionData:
      type: array
      items:
        $ref: '#/components/schemas/PredictionItem'
    PredictionItem:
      type: object
      properties:
        Positive:
          type: string
          description: Positive confidence percentage
        Negative:
          type: string
          description: Positive confidence percentage
    ErrorResponse:
      type: object
      example:
        error: Error message goes here
      properties:
        error:
          type: string